#IDLE_MODE_TIME = 90
#ATTRACT_MODE_TIME = 30
#WELCOME_MODE_TIME = 30
#SCARE_MODE_TIME = 10

IDLE_MODE_TIME = 5
ATTRACT_MODE_TIME = 5
WELCOME_MODE_TIME = 2
SCARE_MODE_TIME = 2

IDLE_KEY = "i"
ATTRACT_KEY = "a"
WELCOME_KEY = "w"
SCARE_KEY = "s"
